### PR TITLE
Beep on the 1

### LINKED ISSUE #15: Beep on the '1'
Currently when you click play and it's the first beep, it won't beep the first time around.
This should be fixed

### PR DESCRIPTION
**Pull request by mark-gerarts**
Fixes #15

### CODE REVIEW

**Comment by joereynolds** [comment]
This doesn't seem to fix the problem :(

For example, refresh the browser and click 'play' you should hear the beep straight away but we don't
it still seems to behave as before

**Comment by mark-gerarts** [comment]
Hm, did I understand the issue incorrectly maybe?

As it is now, when you press play, you have to wait a bit for the first beep (at step 2). With this change, the moment you press play, the metronome will go to step 2 and you'll hear a beep.

Or do you mean it should play the high frequency sound when pressing play?

**Comment by joereynolds** [comment]
Sorry, I meant it should play the high frequency sound when pressing play. :)

**Comment by mark-gerarts** [comment]
By making the initial timesThrough value start at -1, combined with the previous change to tick once when clicking play, it should now work as you described.

**Pull request merged**
