### PR TITLE
Fixed note type won't automatically update #1

### PR DESCRIPTION
**Pull request by ducmtran**
Just one line fixes that. Also, I found that the line `elements.tempo.addEventListener('input', update)` redundant because the function `updateBeatCounter()` already updates it after each beat. #1 
Ps: yay my first github pull request
Ps2: I made two commits because I did not realize others were also making commits while I was working so I have to do another merge commit. Is this what people usually have to do? Or did I do anything wrong?

### CODE REVIEW

**Comment by mark-gerarts** [comment]
Regarding your second edit: [here](https://gist.github.com/Chaser324/ce0505fbed06b947d962#keeping-your-fork-up-to-date) is a little tutorial on how you can rebase your branch. If you have the time you can read the whole gist, it's pretty thorough :)

**Comment by joereynolds** [comment]
Hi, thanks for the PR!

I haven't reviewed it yet but the reason for `elements.tempo.addEventListener('input', update)` was so that the BPM label will update as you slide the tempo slider, without this, I think it will only update on each tick.

Either way, I'll review it after work today, good job :)

**Comment by ducmtran** [comment]
@joereynolds  You are right, my bad. I mistook that line for the note type for some reason :D
@mark-gerarts thanks, will check that out

**Comment by joereynolds** [comment]
I've merged it in and re-instated the tempo slider's event handler :)

**Pull request merged**
